jaeger-operator update image to latest 1.43.0 and bump chart version
jaegertracing/helm-charts pull request #464
Opened 2023-04-06 03:22 UTC by christopheroconnell

#### What this PR does

Update Jaeger operator image version to latest upstream release 1.43.0
Update Jaeger operator Helm chart version to 2.42.0

#### Checklist

- [x] [DCO](https://github.com/jaegertracing/helm-charts/blob/main/CONTRIBUTING.md#sign-off-your-work) signed
- [x] Commits are [GPG signed](https://docs.github.com/en/github/authenticating-to-github/about-commit-signature-verification)
- [x] Chart Version bumped
- [x] Title of the PR starts with chart name (`[jaeger]` or `[jaeger-operator]`)
- [x] README.md has been updated to match version/contain new values

2023-04-06 07:16 UTC, cpanato requested changes
thanks!
please check the comments and sign the DCO

2023-04-06 07:16 UTC, cpanato commented on charts/jaeger-operator/Chart.yaml
>  version: 2.41.0
need to bump the chart version

2023-04-06 07:16 UTC, cpanato commented on charts/jaeger-operator/Chart.yaml
>  version: 2.41.0
`2.42.0`

2023-04-06 15:30 UTC, christopheroconnell commented on charts/jaeger-operator/Chart.yaml
>  version: 2.41.0
done my mistake.

2023-04-10 19:07 UTC, batazor commented
@christopheroconnell Please update [COMPATIBILITY.md](https://github.com/jaegertracing/helm-charts/blob/main/charts/jaeger-operator/COMPATIBILITY.md) by [link](https://github.com/jaegertracing/jaeger-operator/blob/main/COMPATIBILITY.md) and we can merge

2023-04-10 20:15 UTC, christopheroconnell commented
> @christopheroconnell Please update [COMPATIBILITY.md](https://github.com/jaegertracing/helm-charts/blob/main/charts/jaeger-operator/COMPATIBILITY.md) by [link](https://github.com/jaegertracing/jaeger-operator/blob/main/COMPATIBILITY.md) and we can merge

Complete

2023-04-10 22:19 UTC, batazor approved these changes

2023-04-10 22:22 UTC, batazor commented
@christopheroconnell Yes, everything is fine. The only thing is that you have to sign commits, you can read how to do that [here](https://docs.github.com/en/authentication/managing-commit-signature-verification/about-commit-signature-verification ).

2023-04-11 18:06 UTC, christopheroconnell commented
> @christopheroconnell Yes, everything is fine. The only thing is that you have to sign commits, you can read how to do that [here](https://docs.github.com/en/authentication/managing-commit-signature-verification/about-commit-signature-verification).

@batazor Complete. Sorry about that.

2023-04-11 19:51 UTC, merged