[jaeger] Adding optional initContainers for jaeger query and ingester deployments
jaegertracing/helm-charts pull request #537
Opened 2024-01-19 10:58 UTC by ninad-opsverse

#### What this PR does
Adds optional initContainers for jaeger query and ingester deployments

#### Which issue this PR fixes
- fixes #512

#### Checklist

- [X] [DCO](https://github.com/jaegertracing/helm-charts/blob/main/CONTRIBUTING.md#sign-off-your-work) signed
- [X] Commits are [GPG signed](https://docs.github.com/en/github/authenticating-to-github/about-commit-signature-verification)
- [X] Chart Version bumped
- [X] Title of the PR starts with chart name (`[jaeger]` or `[jaeger-operator]`)
- [] README.md has been updated to match version/contain new values

2024-01-19 13:08 UTC, mehta-ankit requested changes

2024-01-19 13:08 UTC, mehta-ankit commented on charts/jaeger/templates/query-deploy.yaml
> +      {{- if .Values.query.initContainers }}
we should add default value in values.yaml file
`initContainers: []`
similar to: https://github.com/jaegertracing/helm-charts/blob/main/charts/jaeger/values.yaml#L521

2024-01-19 13:09 UTC, mehta-ankit commented
Also you have 2 commits and 1 is unverified.
Can you squash all into 1 commit and gpg sign it please.

2024-01-22 08:31 UTC, ninad-opsverse commented
Hey @mehta-ankit, I have squashed all the commits in one commit and gpg signed it. I also have added the default initContainers values in the values file. Please review the updated changes.

2024-01-22 13:23 UTC, mehta-ankit approved these changes
LGTM

2024-01-22 13:30 UTC, merged